import os
import sys
import json

# Ensure backend path is in sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(SCRIPT_DIR)
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from garmin_client import GarminClient

# Dummy workout JSON structure
dummy_workout = {
    "workoutName": "AI Generated Test Workout",
    "description": "A test workout generated by AI Coach",
    "sport": "RUNNING",
    "steps": [
        {
            "type": "WorkoutStep",
            "stepId": 1,
            "stepOrder": 1,
            "intensity": "WARMUP",
            "description": "Warm up",
            "durationType": "TIME",
            "durationValue": 600,  # 10 minutes
            "targetType": "HEART_RATE",
            "targetValueOne": 130,
            "targetValueTwo": 150
        },
        {
            "type": "WorkoutStep",
            "stepId": 2,
            "stepOrder": 2,
            "intensity": "INTERVAL",
            "description": "Run Hard",
            "durationType": "DISTANCE",
            "durationValue": 1000,  # 1 km
            "targetType": "PACE",
            "targetValueOne": 240,  # 4:00 min/km (seconds per km)
            "targetValueTwo": 270   # 4:30 min/km
        },
        {
            "type": "WorkoutStep",
            "stepId": 3,
            "stepOrder": 3,
            "intensity": "COOLDOWN",
            "description": "Cool Down",
            "durationType": "TIME",
            "durationValue": 300,  # 5 minutes
            "targetType": "HEART_RATE",
            "targetValueOne": 120,
            "targetValueTwo": 140
        }
    ]
}

def test_upload():
    # Provide a user ID that has credentials in Firestore
    user_id = "test_user_id" 
    
    # You might need to change this to a real user ID or handle the error
    print(f"Testing upload for user: {user_id}")
    
    try:
        client = GarminClient(user_id)
        # We need to make sure credentials exist first. If not, this will fail.
        # But this is just a script to look at.
        client.upload_workout(dummy_workout)
    except Exception as e:
        print(f"Test failed: {e}")

if __name__ == "__main__":
    test_upload()
